name: Dustin Gilmore
favicon: null
layout_spectrum: 0.8516973974183202
typography_spectrum: 0.052093870704993606
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4802310534287244
  lightness: 0.4640452472958714
  saturation: 0.6837857060600072
  rhythmicContrast: 0.6243681863415986
purpose: []
