name: Dustin Gilmore
favicon: null
layout_spectrum: 0.0106
typography_spectrum: 0.73699
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020202'
    - '#a25d60'
    - '#c59588'
    - '#61a1d3'
  brandStrength: 0.5625
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
